### ISSUE TITLE
Sanitizer needs a tweak

### ISSUE THREAD

**Issue by ocaisa** [easybuilders/JSC#5]
Your script that sanitises these easyconfigs may need a tweak:

https://github.com/easybuilders/JSC/blob/master/Golden_Repo/2018a/i/impi/impi-2018.2.199-iccifort-2018.2.199-GCC-5.5.0.eb

and I also saw problems in the numpy.py easyblock

**Comment by damianam** [comment]
Took me a bit to find the time to do it, but it is done now. I'll upload the changes in a few minutes.

**Comment by damianam** [comment]
Thanks BTW!
